### ISSUE TITLE
Convert a file works but not completely

### ISSUE THREAD

**Issue by rsa-deltacode** [briantbutton/meshwriter-font#2]
I followed your doc well, several times, with different fonts.

Every time everything goes well but when I open the converted font file(.js), only the numbers are present and I don't know why.

    return function(codeList){

      var font={reverseHoles:false,reverseShapes:true},nbsp=' ';

      font["0"]        = {
        sC             : [
                           'IkH2 IkE` IkDUIJCm I*B¦HpB< H3AvG^AQ FªA-E¿A- E2A-D]AQ C©AvCJB< B±B¦BnCm BLDUBLE` BLH2 BLI<BmJ$ B°J±CIKU C¨K¿DZL@ E0LeE½Le F©LeG[L@ H1K¿HnKU I)J±IJJ$ IkI<IkH2'
                         ],
        hC             : [
                           ['G£E5 G£GS D8D£ DJBiE¿Bi G£BiG£E5','D7H^ D7F7 G¡H­ GwI¿G>Jc F©K&E½K& E(K&DpJV D7I¨D7H^']
                         ],
        xMin           : 69,
        xMax           : 532,
        yMin           : -10.5,
        yMax           : 721,
        wdth           : 600
      };
      font["1"]        = {
        sC             : [
                           'GQLO GQAB EfAB EfJ/ B{I* B{Jy GBLO GQLO'
                         ],
        xMin           : 92,
        xMax           : 391.5,
        yMin           : 0,
        yMax           : 710.5,
        wdth           : 600
      };
      font["2"]        = {
        sC             : [
                           'IdB} IdAB B(AB B(Bd ExF] F2FÀFYGO F¤G¥F»H, G/HVG9H{ GCHÁGCIC GCIuG4IÀ G$JGF¬Jf FnJ¥FFJ¶ EÁK"EnK" DoK"D2J_ CwI¼CwHÂ A¯HÂ A¯I}B-JN BOJÄB±K_ CMK¿D&L? D¤LdErLd F[LdG-LE G¢L%H7Kq HqK:H°Jq I*J%I*IM I*H­H¸HL H£G±HYGQ H3F¶G¢FU GJEºF¯EV DJB} IdB}'
                         ],
        xMin           : 37,
        xMax           : 528.5,
        yMin           : 0,
        yMax           : 720.5,
        wdth           : 600
      };
      font["3"]        = {
        sC             : [
                           'DLF: DLGs EXGs E¸GsFCG¥ FrGµF²H/ G.HMG=Hv GLHÁGLIO GLJ6F¹Jo F`K%EsK% EBK%D½J» DrJ­DSJq D6JUD$J0 C·I®C·I] B+I] B+J0BMJy BoK?C*Kt CgL&D9LE D¯LdEpLd FTLdG(LI G}L/H7K} HtKJH·J¡ I5J2I5IO I5I$I)Hz H¿HMH¥H# HiG|HAGW G¼G3GdF¾ H#F¨HPFb H}F>HºE¶ I2EhI>E5 IJD§IJDP IJCmI%BÁ H¤BPHAA¾ G¥AgG+AJ FTA.EpA. DµA.D>AG CkAbC*A¶ BkBEBDB³ AÁC[AÁD= C«D= C«C²C»Ch D)C?DHC# DgB«D´By E<BiEsBi FbBiFÄC# GbC`GbDO GbD¯GOE9 G<EfF½E¥ FxEÂFFF- E¸F:EXF: DLF:'
                         ],
        xMin           : 46,
        xMax           : 516,
        yMin           : -10,
        yMax           : 720.5,
        wdth           : 600
      };
      font["4"]        = {
        sC             : [
                           'HZLO HZE: I°E: I°C¡ HZC¡ HZAB FrAB FrC¡ A«C¡ A¥D¯ FjLO HZLO'
                         ],
        hC             : [
                           ['FXIk CsE: FrE: FrI» FXIk']
                         ],
        xMin           : 32,
        xMax           : 549.5,
        yMin           : 0,
        yMax           : 710.5,
        wdth           : 600
      };
      font["5"]        = {
        sC             : [
                           'D:FU B£F¦ CMLO IFLO IFJ¡ D±J¡ DkH- D¯HAEEHT E¡HgFHHg G-HgG}HE HLH#H¥Gg I9G(IVFO IuExIuD« IuD$IXCO I<ByH¦B8 HJAyGtAS F¿A.F%A. EMA.D|AH D*AcCkA· C+BFB¥Bµ BZC^BTD@ D6D@ DCCWD¦BÃ EBBiF%Bi F`BiF­B¡ G5B¶GRC: GoCbG}Cº G­DMG­D° G­EKG{E¢ GkF2GJFX G*F¡F{F¶ FJG)E®G) EbG)ECG! E$F¿D°F´ DvF©DcFw DNFgD:FU'
                         ],
        xMin           : 73,
        xMax           : 537,
        yMin           : -10,
        yMax           : 710.5,
        wdth           : 600
      };
      font["6"]        = {
        sC             : [
                           'GwLU G³LU G³J± G¤J± F«J±F2Jm E]JKE!I´ DjIWDLH® D.H>D%Gh D=G¥D]G¼ D{H1DÂHD EDHWEpHd E½HoFKHo G3HoG£HF HMGÁH¢G] I0F½IIFE IbEpIbD¶ IbD-IBCT I#B}HjB; H.AzGYAT F¦A.E¸A. DÄA.DHA] CpA­C3BV BxC"BXC« B9DmB9E[ B9F5 B9FÁBHG¥ BXHgB|I? BÀI»CTJd C¯K-DYKd E&K¼E°L7 FuLUGwLU'
                         ],
        hC             : [
                           ['E¶G1 ElG1EFG$ DÄF¼D¥F¦ DcFnDJFN D2F/D"E¬ D"EG D"DqD6D/ DICoDkCB D¯B¹E6B£ EbBkEµBk FIBkFuB£ FÂB¸G=C< GZCdGkC» G{DMG{D¯ G{EHGlE~ G]F2G?F[ G!F¦FxF½ FLG1E¶G1']
                         ],
        xMin           : 59.5,
        xMax           : 527.5,
        yMin           : -10,
        yMax           : 713.5,
        wdth           : 600
      };
      font["7"]        = {
        sC             : [
                           'IqLO IqKM E6AB C@AB G{J° A»J° A»LO IqLO'
                         ],
        xMin           : 43,
        xMax           : 535,
        yMin           : 0,
        yMax           : 710.5,
        wdth           : 600
      };
      font["8"]        = {
        sC             : [
                           'IPIX IPHqH½GÁ HeGMGªFÁ H<F©HhFc H´F?I/E¶ INEhI_E3 IoD¢IoDD IoCcIJB¸ I%BIHhA¹ H)AdGTAH F£A.EÂA. E<A.DhAH C´AdCSA¹ B·BIBrB¸ BMCcBMDD BMD¢B^E4 BnEiB®E· C)F@CSFd C¡F©D3FÁ CWGMC!GÁ BnHqBnIX BnJ7B±J¤ C.KKChK~ CÃL/DpLI E>LdE¿Ld F{LdGILI G¼L/HTK~ H±KKI/J¤ IPJ7IPIX'
                         ],
        hC             : [
                           ['GgIQ GgI¢GXJ& GIJOG/Jl F·JªFpJº FIK%E¿K% EoK%EJJ» E$J¬D¯Jn DsJQDeJ* DWI¥DWIQ DWHÃDfHy DtHQD°H5 E&G¼ELG¬ ErG{EÂG{ FLG{FrG¬ F¹G¼G0H5 GJHQGXHy GgHÃGgIQ','G§DP G§D©GuE2 GdE_GEE~ G&E¿F}F- FRF>EÀF> EiF>E>F- D¶E¿DwE~ DXE_DHE2 D8D©D8DP D8CdDvC% E3BiEÂBi FRBiF}By G&B«GEC% GdCDGuCp G§C¼G§DP']
                         ],
        xMin           : 69.5,
        xMax           : 534,
        yMin           : -10,
        yMax           : 720.5,
        wdth           : 600
      };
      font["9"]        = {
        sC             : [
                           'CªB¦ C»B¦ DºB¦EoBÄ FDC>F{Ct G/D(GIDq GdE7GkE® GUEtG9E_ FÀEIF{E9 FXE)F.DÃ E¨D¹ESD¹ DkD¹CÀE> CPEfBÀF& BkFjBRG? B9G¸B9Ht B9IYBWJ4 BvJ±C0KQ CkK¸D@L< D¸LdE¦Ld FzLdGPL4 H(K¨HcK6 H¿JhI9I¡ IUH¸IUGÄ IUGU IUFpIHE° I;E+H¾DR H}C{HGC0 G¶BgGEB/ FyAzE±AZ E#A<C¼A< CªA< CªB¦'
                         ],
        hC             : [
                           ['E¦FO F+FOFOF] FuFiFµF¢ G0F¸GHG4 G`GTGnGz GnHF GnH¿GZI_ GGIÃG&JL F©JzF]J² F2K$E¦K$ ELK$E!J± DyJxD[JN D>J%D/Ip CÃI8CÃH{ CÃH?D.G¬ D;GTDWG* DtF¤DÁFi EIFOE¦FO']
                         ],
        xMin           : 59.5,
        xMax           : 521.5,
        yMin           : -3,
        yMax           : 720.5,
        wdth           : 600
      };

      return font;
    }

**Comment by temrysh** [comment]
Same issue here, any updates?

**Comment by briantbutton** [comment]
My guess is that the config file is missing.  Consider the 'coverage' variable in index.js.

If you look at lines 30 through 40 in index.js, it (clumsily) picks up coverage for the font by name (in lower case).  If that is absent, it looks for default-coverage.  If that is absent, it just covers the numerals.

Note that it also prints the coverage, making it easy for you to see what glyphs it is building.

Hope that helps.

**Comment by temrysh** [comment]
@briantbutton Thank you!
After adding `coverage` it gives the correct output. Might be a good idea to add that into `README`.
